CONTRIBUTING.md, NOTICE.md, README.md, releng/org.eclipse.rap.build/pom.xml
With the migration from Gerrit/cgit to GitHub, the SCM URL that is added
to all MANIFEST.MF files during build time needs to be changed. Update
this to reflect the migration.
Bug: https://github.com/eclipse-rap/org.eclipse.rap/issues/1
Signed-off-by: Markus Knauer <mknauer@eclipsesource.com>
=> Update Git repo and issue tracker URLs to GitHub

releng/org.eclipse.rap.build/pom.xml
Use the very same JUnit version 4.13.2 in the Tycho Maven dependencies
as the one provided by the Eclipse Orbit project. This also mitigates a
local information disclosure vulnerability in older JUnit libraries.
=> Synchronise JUnit version

bundles/org.eclipse.rap.nebula.widgets.grid/src/org/eclipse/nebula/widgets/grid/Grid.java
Bug 571201: [RAP] [Grid] Selecting a cell is not possible when the
markup contains an img tag
https://bugs.eclipse.org/bugs/show_bug.cgi?id=571201
=> Add documentation how to use Grid cell selection with markup

features/org.eclipse.rap.e4.equinox.target.feature/feature.xml, features/org.eclipse.rap.equinox.target.feature/feature.xml
The Java package provided by this package was formerly provided
internally by the bundle `org.eclipse.equinox.preferences` and has been
moved to a bundle of its own. In order to satisfy all downstream
dependencies include the OSGi bundle now in both RAP Equinox features.
=> Include org.osgi.service.prefs bundle in RAP Equinox features

bundles/org.eclipse.rap.rwt/js/rwt/scripting/EventProxy.js
The `count` property can be used to determine the mouse wheel scroll
direction by its sign. This property is set for `MouseDown`, `MouseUp`,
`MouseDoubleClick`, and `MouseWheel` client scripting events.
Fix #20
=> Add "count" property to EventProxy

bundles/org.eclipse.rap.rwt/js/rwt/widgets/DateTimeDate.js
For years below 01/01/1970 00:00:00 the time in milliseconds is
negative.
In JS the Number.MIN_VALUE "is NOT the most negative number", but the
"the smallest positive numeric value closed to zero".
Changing Number.MIN_VALUE to - Number.MAX_VALUE solves the problem.
Fix #29
=> Fix an issue with year picked from the calendar below 1970

bundles/org.eclipse.rap.rwt/js/rwt/remote/handler/MenuItemHandler.js, bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/widgets/MenuItem.java, bundles/org.eclipse.rap.rwt/widgetkits/org/eclipse/swt/internal/widgets/menuitemkit/MenuItemLCA.java, examples/org.eclipse.rap.demo.controls/src/org/eclipse/rap/demo/controls/ShellTab.java, tests/org.eclipse.rap.rwt.test/src/org/eclipse/swt/internal/widgets/menuitemkit/MenuItemLCA_Test.java, tests/org.eclipse.rap.rwt.test/src/org/eclipse/swt/widgets/MenuItem_Test.java
Add new API:
- org.eclipse.swt.widgets.MenuItem.setToolTipText(String)
- org.eclipse.swt.widgets.MenuItem.getToolTipText()
To have a tooltip with markup, the RWT.TOOLTIP_MARKUP_ENABLED must be
set as data on the item.
Fix #30
=> Add support for MenuItem tooltip text

bundles/org.eclipse.rap.rwt/js/rwt/remote/handler/DisplayHandler.js, bundles/org.eclipse.rap.rwt/js/rwt/widgets/Display.js, bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/client/WebClient.java, bundles/org.eclipse.rap.rwt/widgetkits/org/eclipse/swt/internal/widgets/displaykit/DisplayLCA.java, tests/org.eclipse.rap.rwt.test/src/org/eclipse/swt/internal/widgets/displaykit/DisplayLCA_Test.java
In certain circumstances it is needed to prevent the execution of
`sendShutdown` within the JavaScript part of RAP. One reason for doing so
is the proper handling of a HTTP redirect response (HTTP code 302/303).
Add the new entry point property `WebClient.DISABLE_SHUTDOWN_REQUEST`
that can be set in the `ApplicationConfiguration`.
Fix #33
=> Add possibility to disable shutdown request

bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/StackRenderer.java, bundles/org.eclipse.e4.ui.workbench.swt/.classpath, bundles/org.eclipse.e4.ui.workbench.swt/build.properties, bundles/org.eclipse.e4.ui.workbench.swt/src-rap/org/eclipse/e4/ui/internal/workbench/swt/StylingEngineImpl.java, bundles/org.eclipse.e4.ui.workbench.swt/src/org/eclipse/e4/ui/internal/workbench/swt/E4Application.java
The e4 CSS styling engine is not available in the RAP port. Style active
part stack manually in custom StylingEngineImpl class.
The Activate event in RAP does not have a "detail" flag set. Always
activate part stack regardless this flag.
=> Fix e4 part stack styling and activation

features/org.eclipse.rap.e4.equinox.target.feature/feature.xml, features/org.eclipse.rap.equinox.target.feature/feature.xml
The dependency chain of the upstream OSGi bundles (in particular the
Configuration Admin bundle `org.eclipse.equinox.cm`) has changed and
require the inclusion of two additional OSGi bundles:
`org.osgi.service.cm` and `org.osgi.service.event`. Add these bundles
including their source bundles to the Equinox features.
=> Include new OSGi package dependencies in Equinox features

features/org.eclipse.rap.e4.equinox.target.feature/feature.xml, features/org.eclipse.rap.equinox.target.feature/feature.xml
There are still dependencies from OSGi missing. In order to provide a
verifiable M1 build, add all required bundles, and review the list after
delivering M1.
=> Fix remaining dependency issues by adding more OSGi service bundles

bundles/org.eclipse.rap.fileupload/META-INF/MANIFEST.MF, examples/org.eclipse.rap.demo.controls/launch/RAP Controls Demo.launch, examples/org.eclipse.rap.examples/launch/RAP Examples Demo.launch, features/org.eclipse.rap.e4.equinox.target.feature/feature.xml, features/org.eclipse.rap.equinox.target.feature/feature.xml, releng/org.eclipse.rap.examples.build/rapdemo/org.eclipse.rap.examples.rapdemo.product, tests/org.eclipse.rap.fileupload.test/META-INF/MANIFEST.MF
This change also includes Apache `commons-io` in version 2.11.0.
Update lower version boundaries of Apache `commons-fileupload` and
`commons-io` to the version of the updated bundles in order to ensure
that the correct versions are selected at runtime.
The new bundles are consumed from Eclipse Platform which retrieves them
from Maven Central. As part of this process, the bundle symbolic name of
the bundles changed:
- `org.apache.commons.fileupload` to `org.apache.commons.commons-fileupload`
- `org.apache.commons.io` to `org.apache.commons.commons-io`
Update features, demo launch configurations, and demo product
definitions to the new name.
This fixes #41.
=> Upgrade Apache commons-fileupload to version 1.4.0

bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/RWTProperties.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/textsize/TextSizeUtil.java, tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/internal/RWTProperties_Test.java, tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/internal/textsize/TextSizeUtil_Test.java
Eliminating text size determination requests for load testing is a
manual work that is not error prone. Always use text size estimation for
load testing automatically.
- add new system property "org.eclipse.rap.rwt.enableLoadTests"
- do not send texts and probes for measurement if the property above is
set
- fill TextSizeStorage and ProbeResultStore with estimated values on
first request
=> Disable text size measurement for load testing

bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/textsize/TextSizeUtil.java, tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/internal/textsize/TextSizeUtil_Test.java
For performance reasons keep the value of the system property in a
static field.
=> Don't query "o.e.r.rwt.enableLoadTests" system property all the time

bundles/org.eclipse.rap.rwt/js/rwt/widgets/Grid.js
The current code for skipping invisible cells when keyboard navigation is used was not working correctly with hidden first or last column. Search for the next visible cell in a more clear way.
Fix #69
=> Fix cell navigation with invisible columns

bundles/org.eclipse.rap.rwt/js/rwt/widgets/Grid.js, tests/org.eclipse.rap.rwt.jstest/RWT Client Tests.launch
When Grid auto-height is enabled, all rows must be updated after items text is set. Under some conditions this is not the case.
Ensure that all rows are rendered after items text is set.
Fix #75
=> Fix item height with auto-height enabled on Grid creation

examples/org.eclipse.rap.demo.controls/launch/RAP Controls Demo.launch, examples/org.eclipse.rap.demo/launch/RAP Workbench Demo (Business).launch, examples/org.eclipse.rap.demo/launch/RAP Workbench Demo (Fancy).launch, examples/org.eclipse.rap.demo/launch/RAP Workbench Demo (OSGi).launch, examples/org.eclipse.rap.demo/launch/RAP Workbench Demo.launch, examples/org.eclipse.rap.examples/launch/RAP Examples Demo.launch, features/org.eclipse.rap.e4.equinox.target.feature/feature.xml, features/org.eclipse.rap.equinox.target.feature/feature.xml, tests/org.eclipse.rap.rwt.jstest/RWT Client Tests.launch
Use the same slf4j.api bundle as Eclipse Platform that retrieves it from Maven Central instead of the older outdated one from Eclipse Orbit.
Please note that this changes the bundle symbolic name from org.slf4j.api to the shorter slf4j.api which requires to adjust all launch configurations.
This change is supposed to replace pull request #61.
Its companion change in RAP Tools is eclipse-rap/org.eclipse.rap.tools/pull/28.
=> Synchronise SLF4J plugin to Eclipse Platform

releng/org.eclipse.rap.build/repository.e4/pom.xml, releng/org.eclipse.rap.build/repository/pom.xml
Enable the includeAllDependencies switch when assembling the final distribution p2 repositories. This ensures that all (transitive) dependencies are included and that the resulting p2 repository is self-contained.
In particular this change leads to the inclusion of the SLF4J NOP implementation bundle into the p2 repository unless RAP or any of the upstream projects decide to provide a different implementation. We do not include it in any of our features to make it more unlikely that it gets mirrored into other p2 repositories, or used in any real products.
This is a follow up and enhancement of #80, and should help by implementing eclipse-platform/eclipse.platform.releng.aggregator/issues/588 in the future.
=> Automatically include all dependencies in output p2 repositories

examples/org.eclipse.rap.demo.controls/launch/RAP Controls Demo.launch, examples/org.eclipse.rap.demo/launch/RAP Workbench Demo (Business).launch, examples/org.eclipse.rap.demo/launch/RAP Workbench Demo (Fancy).launch, examples/org.eclipse.rap.demo/launch/RAP Workbench Demo (OSGi).launch, examples/org.eclipse.rap.demo/launch/RAP Workbench Demo.launch, examples/org.eclipse.rap.examples/launch/RAP Examples Demo.launch
SLF4J implementation is required for successful execution.
=> Add "slf4j.nop" bundle to all demo launch configurations

bundles/org.eclipse.rap.filedialog/META-INF/MANIFEST.MF, bundles/org.eclipse.rap.fileupload/META-INF/MANIFEST.MF, bundles/org.eclipse.rap.nebula.widgets.grid/META-INF/MANIFEST.MF, bundles/org.eclipse.rap.nebula.widgets.richtext/META-INF/MANIFEST.MF, bundles/org.eclipse.rap.rwt.osgi/META-INF/MANIFEST.MF, bundles/org.eclipse.rap.rwt/META-INF/MANIFEST.MF, bundles/org.eclipse.rap.ui.workbench/META-INF/MANIFEST.MF, bundles/org.eclipse.rap.ui/META-INF/MANIFEST.MF, examples/org.eclipse.rap.demo.controls/META-INF/MANIFEST.MF, examples/org.eclipse.rap.demo/META-INF/MANIFEST.MF, examples/org.eclipse.rap.examples.pages/META-INF/MANIFEST.MF, examples/org.eclipse.rap.examples/META-INF/MANIFEST.MF, examples/org.eclipse.rap.filedialog.demo.examples/META-INF/MANIFEST.MF, tests/org.eclipse.rap.fileupload.test/META-INF/MANIFEST.MF, tests/org.eclipse.rap.rwt.cluster.test/META-INF/MANIFEST.MF, tests/org.eclipse.rap.rwt.cluster.testfixture/META-INF/MANIFEST.MF, tests/org.eclipse.rap.rwt.jstest/META-INF/MANIFEST.MF, tests/org.eclipse.rap.rwt.test/META-INF/MANIFEST.MF, tests/org.eclipse.rap.rwt.testfixture/META-INF/MANIFEST.MF
Tomcat 10.x has an automated tool for converting "javax.servlet" package imports to "jakarta.servlet". The upper version constraint prevents the conversion process to produce a working war file.
A 5+ version of "javax.servlet" is extremely unlikely, and therefore the upper version constraint is useless.
=> Remove upper version constraint from "javax.servlet.*" package imports

bundles/org.eclipse.rap.rwt/js/rwt/remote/Request.js
In case of connection error, fetch throws an error. Connection.js#_isConnectionError relies on status = 0 in order to recognize it.
Set status to zero in fecth catch block.
=> Improve connection error handling when fetch is used

bundles/org.eclipse.rap.rwt/js/rwt/runtime/ErrorHandler.js
With the latest changes, when press on the 'retry' button, browser pops a message 'Are you sure to leave page?'
With this change that message does not appear.
=> Improve connection "retry" behavior  in ErrorHandle.js

bundles/org.eclipse.rap.rwt/js/rwt/event/DomEvent.js, bundles/org.eclipse.rap.rwt/js/rwt/scripting/EventProxy.js
When you press the ALT GR Key in a SWT Application the flags for SWT.CTRL and SWT.ALT are both set in the stateMask Property of the Event. However this does not work on RAP.
=> Add support for the altgr modifier as a combination of CTRL and ALT (like in SWT)

bundles/org.eclipse.rap.rwt/js/rwt/widgets/Display.js, bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/service/StartupJson.java, tests/org.eclipse.rap.rwt.jstest/RWT Client Tests.launch, tests/org.eclipse.rap.rwt.jstest/js/org/eclipse/rwt/test/tests/DisplayTest.js, tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/internal/service/StartupJson_Test.java
The initial RAP request POST or GET does not initiate UI session. There is a client service StartupParameters to extract the startup  parameters from URL query string and send them to the server with the first UI request. With the initial POST request this is not working.
In order to fix it, get the startup parameters from the initial GET/POST request on the server and send them back to client-side Display object during the creation in StartupJson#appendCreateDisplay.
Fix #58
=> Add possibility to get startup parameters from initial POST request

bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/internal/graphics/InternalImageFactory.java, tests/org.eclipse.rap.rwt.test/src/org/eclipse/swt/internal/graphics/InternalImageFactory_Test.java
In some cases it will be useful to destroy the internal image. This includes:
* remove the internal image from `InternalImageFactory.cache`
* deregister the resource from `ResourceManager` to remove the file from the file system
=> Add internal API to destroy internal image

bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/serverpush/ServerPushManager.java, tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/internal/serverpush/ServerPushManager_Test.java
Introduce request release interval to specify the minimum time required to released the blocked server push request.
=> Improve the performance for frequently (<100ms) updates

bundles/org.eclipse.rap.rwt.osgi/src/org/eclipse/rap/rwt/osgi/internal/HttpSessionWrapper.java, bundles/org.eclipse.rap.rwt.osgi/src/org/eclipse/rap/rwt/osgi/internal/ServletContextWrapper.java, tests/org.eclipse.rap.rwt.osgi.test/src/org/eclipse/rap/rwt/osgi/internal/HttpSessionWrapper_Test.java, tests/org.eclipse.rap.rwt.osgi.test/src/org/eclipse/rap/rwt/osgi/internal/ServletContextWrapper_Test.java
The following APIs have been deprecated since Servlet 2.x and removed in
Servlet 6:
* ServletContextWrapper
- getServlet(String)
- getServlets(),
- getServletNames(),
- log(Exception, String)
* HttpSessionWrapper
- getValue(String)
- getValueNames()
- putValue(String, Object)
- removeValue(String)
There is no replacement for getSessionContext() as the complete class
HttpSessionContext is deprecated. Keep it for now.
For others use their replacement instead.
=> Don't delegate to deprecated servlet APIs

bundles/org.eclipse.rap.nebula.widgets.grid/src/org/eclipse/nebula/widgets/grid/Grid.java, tests/org.eclipse.rap.nebula.widgets.grid.test/src/org/eclipse/nebula/widgets/grid/Grid_Test.java
To avoid invalid selected cells when items are reduced, we have to clear the cell selection.
Fix #135
=> Clear selected cells when setting lower item count

bundles/org.eclipse.rap.fileupload/src/org/eclipse/rap/fileupload/internal/FileUploadProcessor.java, tests/org.eclipse.rap.fileupload.test/src/org/eclipse/rap/fileupload/internal/FileUploadProcessor_Test.java
If the filename contains mixture of Unix and Windows separators the filename is not stripped correctly.
Use exiting Apache Commons API for getting the file name.
=> Fix handling of file names on Windows

bundles/org.eclipse.rap.rwt/pom.xml, releng/org.eclipse.rap.clientbuilder/META-INF/MANIFEST.MF
Orbit is migrating from hand-crafted bundles to pristine versions from Maven central. Part of this is the bundle symbolic name change from `org.mozilla.javascript` to `org.mozilla.rhino`.
Because this includes an upgrade of the version, the reference in the RWT build needs to be in sync again, otherwise the build breaks.
=> Upgrade to new org.mozilla.rhino version provided by Orbit

bundles/org.eclipse.rap.jface/src/org/eclipse/jface/viewers/IStructuredSelection.java
This would align this to the standard Jface IStructuredSelection, which was made an Iterable long ago:
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=234331
and the corresponding commit: https://git.eclipse.org/c/platform/eclipse.platform.ui.git/commit/bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/IStructuredSelection.java?id=a831a2e350432c0824e8df41f01fcd50390a063a
=> Update IStructuredSelection to make it an Iterable

bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/RWTProperties.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/service/UISessionImpl.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/textsize/MeasurementOperator.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/textsize/ProbeStore.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/textsize/TextSizeStorage.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/textsize/TextSizeStorageUtil.java, tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/internal/RWTProperties_Test.java, tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/internal/textsize/TextSizeStorageUtil_Test.java
Setting org.eclipse.rap.rwt.textSizeStoreSessionScoped=true allows to trade performance for correctness in environments where clients return inconsistent text measurements. By caching the text sizes in the UISession instead of the app context, measurements only have to be consistent within the same client. The downside of this approach is each client has to re-compute each text the first time it is measured.
Fix #22
=> Add mode to make text-size-store UI session scoped

bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/widgets/TimerExecScheduler.java, tests/org.eclipse.rap.rwt.test/src/org/eclipse/swt/widgets/TimerExecScheduler_Test.java
To fix the issue cancel all not executed tasks during the TimerExecScheduler dispose.
Fix: #146
=> Fix a memory leak when disposing the timer with not executed tasks

SECURITY.md
Inline with the new template for SECURITY.md by the Eclipse Foundation:
https://gitlab.eclipse.org/security/best-practices/-/blob/main/templates/SECURITY.md
=> Updating SECURITY.md following template changes

tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/internal/RWTProperties_Test.java, tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/internal/textsize/MeasurementOperator_Test.java, tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/internal/textsize/TextSizeStorageUtil_Test.java
Ensure that TEXT_SIZE_STORE_SESSION_SCOPED is cleared before test execution.
=> Fix randomly failing testInitStartupProbes test

bundles/org.eclipse.rap.ui/plugin.xml
The "org.eclipse.equinox.http.registry.httpcontexts" extension point is renamed to "org.eclipse.rap.http.registry.httpcontexts" as part of bundle rename.
=> Rename extension point

features/org.eclipse.rap.e4.equinox.target.feature/feature.xml
The bundle org.eclipse.e4.emf.xpath has a dependency to the external bundle org.apache.commomns.jxpath which is not developed any more. This bundle itself has dependencies to various Java packages from the javax.servlet.* namespace.
As a short term solution, provide the javax.servlet API by adding the Jakarta servlet 4.0 bundle in addition to the 6.1 version temporarily to the E4 Equinox feature in order to satisfy the runtime only constraint.
=> Provide workaround for E4 javax.servlet dependencies

bundles/org.eclipse.rap.servletbridge/src/org/eclipse/rap/servletbridge/FrameworkLauncher.java, examples/org.eclipse.rap.examples/src/org/eclipse/rap/examples/internal/MainUi.java, examples/org.eclipse.rap.nebula.widgets.grid.demo.examples/src/org/eclipse/rap/nebula/widget/grid/demo/examples/NebulaGridExamplePage.java, releng/org.eclipse.rap.examples.build/controlsdemo/assembly.xml, releng/org.eclipse.rap.examples.build/controlsdemo/org.eclipse.rap.examples.controls.product, releng/org.eclipse.rap.examples.build/controlsdemo/pom.xml, releng/org.eclipse.rap.examples.build/controlsdemo/rootfiles/WEB-INF/web.xml, releng/org.eclipse.rap.examples.build/parent/pom.xml, releng/org.eclipse.rap.examples.build/rapdemo/assembly.xml, releng/org.eclipse.rap.examples.build/rapdemo/org.eclipse.rap.examples.rapdemo.product, releng/org.eclipse.rap.examples.build/rapdemo/pom.xml, releng/org.eclipse.rap.examples.build/rapdemo/rootfiles/WEB-INF/web.xml, releng/org.eclipse.rap.examples.build/workbenchdemo/assembly.xml, releng/org.eclipse.rap.examples.build/workbenchdemo/org.eclipse.rap.examples.workbench.product, releng/org.eclipse.rap.examples.build/workbenchdemo/pom.xml, releng/org.eclipse.rap.examples.build/workbenchdemo/rootfiles/WEB-INF/web.xml
Provide the required updates to make our three examplary .war products build.  
This includes the required changes in the extension bundle for Jakarta Servlet 6, but also the changes required to assemble the .war files, especially the change of dependencies and bundles in the product definitions.
This PR is meant to merged to the main branch as single commits, i.e. not to be squashed into one.
=> RAP4 Java Servlet 6 update for example projects

bundles/org.eclipse.rap.filedialog/src/org/eclipse/swt/widgets/FileDialog.java
Issue: https://github.com/eclipse-rap/org.eclipse.rap/issues/174
=> Disable ok button immediately to avoid "Widget disposed" error

bundles/org.eclipse.rap.nebula.widgets.grid/src/org/eclipse/nebula/widgets/grid/Grid.java
For the Nebula Grid, when the row header is visible, the `getColumn` calculation didn't account for the additional width, and so the incorrect column was returned. The width is now added to the accumulator and so the correct column is always returned, even when clicking on the very edge of the column.
Matches Nebula's code here: https://github.com/eclipse/nebula/blob/master/widgets/grid/org.eclipse.nebula.widgets.grid/src/org/eclipse/nebula/widgets/grid/Grid.java#L1262-L1268.
=> Fix Grid getColumn calculation when row header is visible

bundles/org.eclipse.rap.nebula.jface.gridviewer/META-INF/MANIFEST.MF
Makes sure all packages (for now, just a single internal one) is exported from `org.eclipse.rap.nebula.jface.gridviewer`. Marked as `x-internal` so clients receive warnings when importing them. See upstream Nebula here: https://github.com/eclipse/nebula/blob/master/widgets/grid/org.eclipse.nebula.widgets.grid/META-INF/MANIFEST.MF#L10 (they combined the gridviewer bundle into the grid bundle but the package name is the same).
=> Export all packages from org.eclipse.rap.nebula.jface.gridviewer

bundles/org.eclipse.rap.nebula.widgets.grid/src/org/eclipse/nebula/widgets/grid/internal/gridkit/GridOperationHandler.java, tests/org.eclipse.rap.nebula.widgets.grid.test/src/org/eclipse/nebula/widgets/grid/internal/gridkit/GridOperationHandler_Test.java
The selection event index property was always greater by 1 because of the row header column.
Issue: https://github.com/eclipse-rap/org.eclipse.rap/issues/218
=> Fix selection event index in Nebula Grid

bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/service/StartupJson.java
When using startup POST request in Tomcat, the encoding of the parameters is broken. We need to set the encoding explicitly. The issue is not reproducible in Jetty.
=> Explicitly set request encoding before reading request parameters

bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/engine/RWTServlet.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/service/StartupJson.java
When using startup POST request in Tomcat, the encoding of the parameters is broken. We need to set the encoding explicitly. The issue is not reproducible in Jetty.
The previous commit set the encoding too late (after processing the request).
=> Set POST request encoding before processing the request if not set

bundles/org.eclipse.rap.http.registry/src/org/eclipse/rap/http/registry/internal/FilterManager.java, bundles/org.eclipse.rap.http.registry/src/org/eclipse/rap/http/registry/internal/HttpContextManager.java, bundles/org.eclipse.rap.http.registry/src/org/eclipse/rap/http/registry/internal/ResourceManager.java, bundles/org.eclipse.rap.http.registry/src/org/eclipse/rap/http/registry/internal/ServletManager.java
The extension ponit names has been renamed in RAP 4.0 from "org.eclipse.equinox.http.registry.*" to
"org.eclipse.rap.http.registry.*"
Fix: https://github.com/eclipse-rap/org.eclipse.rap/issues/223
=> Use correct extension point names in Java code

bundles/org.eclipse.rap.servletbridge/src/org/eclipse/rap/servletbridge/FrameworkLauncher.java
When incrementing bundle versions it is important in the future to increment the version of the package export of
`org.eclipse.rap.servletbridge` in the `FrameworkLauncher` to match the new version.
Also update the `EXTENSIONBUNDLE_DEFAULT_VERSION` to use the same version everywhere.
=> Increment org.eclipse.rap.servletbridge package export version

bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/accessibility/AccessibleListener.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/browser/LocationListener.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/browser/ProgressListener.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/custom/CTabFolder2Listener.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/events/ControlListener.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/events/ExpandListener.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/events/FocusListener.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/events/KeyListener.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/events/MenuListener.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/events/MouseListener.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/events/MouseTrackListener.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/events/SelectionListener.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/events/ShellListener.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/swt/events/TreeListener.java
The helper methods to use lambda expressions in SWT listeners are missing in RAP.
Adding them avoids the need to convert existing lambda expressions into adapters in a new single-source application.
=> Add helper methods to use lambda expressions for listeners methods

bundles/org.eclipse.rap.rwt/js/rwt/widgets/DateTimeDate.js
One a date filed (year, month or day) is changed with min/max limit set, DateTime.js#_applyLimitRestriction is called to ensure that the new date in not outside the range. If you set all three fields together, using _setDate, the intermidiate validation (after every filed) can lead to endless recursion.
Avoid calling DateTime.js#_applyLimitRestriction before all the three fields are set.
Fix: https://github.com/eclipse-rap/org.eclipse.rap/issues/253
=> Fix JavaScript error with min/max value set in DateTime

bundles/org.eclipse.rap.fileupload/src/org/eclipse/rap/fileupload/internal/FileUploadServiceHandler.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/engine/RWTServlet.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/service/ServiceManagerImpl.java, bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/util/HTTP.java, tests/org.eclipse.rap.fileupload.test/src/org/eclipse/rap/fileupload/test/FileUploadTestUtil.java, tests/org.eclipse.rap.rwt.test/src/org/eclipse/rap/rwt/internal/util/HTTP_Test.java, tests/org.eclipse.rap.rwt.testfixture/src/org/eclipse/rap/rwt/testfixture/internal/TestRequest.java
With commit
https://github.com/apache/tomcat/commit/3f8a229be8cbdd99e718b1b72b5f9c0ea1421c23 using request#getParameter in Tomcat 11 will parse the request body. As a result the file upload is broken as the request body is already processed in RWTServlet by the getting connection/service handler id.
The fix is to manually parse the query string parameters for multipart requests and not using request#getParameter.
=> Fix file upload in Tomcat 11

bundles/org.eclipse.rap.rwt/js/rwt/remote/handler/BrowserHandler.js, bundles/org.eclipse.rap.rwt/js/rwt/widgets/base/Iframe.js, bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/RWT.java, bundles/org.eclipse.rap.rwt/widgetkits/org/eclipse/swt/internal/browser/browserkit/BrowserLCA.java, tests/org.eclipse.rap.rwt.jstest/js/org/eclipse/rwt/test/tests/BrowserTest.js
Proposing support for setting sandbox and srcdoc attributes of the iframe that represents the Browser widget in RWT.
- It would be good to have the possibility to configure the sandbox attribute of the iframe, regarding security aspects.
- Allowing usage of srcdoc attribute provides an alternative to external static files or larger data urls.
Configuration is done using setData with respective RWT constants.
=> Introduce support for sandbox and srcdoc attributes in Browser.

bundles/org.eclipse.rap.rwt/js/rwt/event/EventHandlerUtil.js
Rewrite EventHandlerUtil.js#applyBrowserFixes to eliminate string based JS code.
Issue: https://github.com/eclipse-rap/org.eclipse.rap/issues/263
=> Fix an error when CSP is applied

bundles/org.eclipse.rap.rwt/widgetkits/org/eclipse/swt/internal/browser/browserkit/BrowserOperationHandler.java
The execution of the `BrowserFunction` is delayed as it's executed in a `ProcessActionRunner`. It's possible to dispose the function before it's actually executed.
Issue: https://github.com/eclipse-rap/org.eclipse.rap/issues/274
=> Do not execute already disposed BrowserFunction

bundles/org.eclipse.rap.jface/src/org/eclipse/jface/viewers/ColumnViewerEditor.java
Fix: https://github.com/eclipse-rap/org.eclipse.rap/issues/282
=> Check that cell isn't null before invoking processTraverseEvent

features/org.eclipse.rap.e4.sdk.feature/feature.xml, features/org.eclipse.rap.sdk.feature/feature.xml
With the migration to Jakarta EE namespace, two additional bundles were moved into the RAP project. Add them to the SDK features in order to make the sources available.
- org.eclipse.rap.servletbridge
- org.eclipse.rap.http.servletbridge
=> Add missing source bundles to SDK features

bundles/org.eclipse.rap.jface/src/org/eclipse/jface/action/ToolBarContributionItem.java
In the original JFace code the chevron button is always visible, but the selection listener is not added to the chevron if not used. This is confusing for the users as there is an UI element that is highlighed, clickable, but without any real response.
=> Hide action bar chevron button if not used

bundles/org.eclipse.rap.rwt/js/rwt/event/EventHandler.js
In some cases it's possible to dispose a widget without removing it from the EventHandler capture widget.
Hangle disposed widget in the same way as disabled in EventHandler#getCaptureWidget and return null.
=> Ensure EventHandler#getCaptureWidget does not return disposed widget

bundles/org.eclipse.rap.rwt/js/rwt/widgets/Shell.js
If you dispose the Shell on mouse click event, but you double clicked, the second event ends up on already disposed shell.
=> Remove event listeners when shell is destroyed

bundles/org.eclipse.rap.rwt/js/rwt/runtime/System.js, bundles/org.eclipse.rap.rwt/src/org/eclipse/rap/rwt/internal/service/rwt-index.html
- the meta "apple-mobile-web-app-capable" is replaced with "mobile-web-app-capable"
- page "unload" event is replaced with "pagehide" due to deprecation [1]
[1] https://developer.chrome.com/docs/web-platform/deprecating-unload
Fix: https://github.com/eclipse-rap/org.eclipse.rap/issues/315
=> Fix Chrome error messages in JS console

bundles/org.eclipse.rap.jface/src/org/eclipse/jface/viewers/AbstractTableViewer.java
In case of non virtual table AbstractTableViewer virtualManager has never been created. Prevent calling "dispose" on null virtualManager.
=> Fix NPE in AbstractTableViewer handleDispose method
